name: CI/CD Deploy Automático

on:
  push:
    branches: [ main ] # Se activa al subir cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Desplegar en AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Actualizar el código del Frontend (donde está el docker-compose)
            cd ~/front_despacho
            git pull origin main
            
            # 2. Asegurar que el docker-compose.yml más reciente esté en el home
            cp docker-compose.yml ~/docker-compose.yml
            
            # 3. Actualizar los Backends
            cd ~/back-Despachos_SpringBoot && git pull origin main
            cd ~/back-Ventas_SpringBoot && git pull origin main
            
            # 4. Reiniciar la orquestación (Docker construye lo nuevo y levanta)
            cd ~
            docker-compose up -d --build